name: Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Install dependencies
        working-directory: /var/www/siva_domain/wordpress/
        run: |
          composer install -o
          npm install

      - name: Build
        run: npm run build

      - name: Sync
        env:
          dest: 'root@13.233.234.149:/var/www/siva_domain/wordpress/wp-content/themes/mytheme'
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          rsync -chav --delete \
            -e 'ssh -i ./private_key -o StrictHostKeyChecking=no' \
            --exclude private_key \
            --exclude .git/ \
            --exclude .github/ \
            --exclude node_modules/ \
            ./ ${{ env.dest }}

